/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ClaseVentanaChat;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nano
 */
public class General extends javax.swing.JFrame {

    VentanaChat V1=new VentanaChat();
    ClaseVentanaChat ventanaChat=new ClaseVentanaChat();
    /**
     * Creates new form General
     */
    public General() {
        initComponents();
        //this.setExtendedState(General.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMAIniciarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMAIniciarSesionMousePressed
        
    }//GEN-LAST:event_itemMAIniciarSesionMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ListaContactos listaContactos=new ListaContactos();
        desktopPane.add(listaContactos);
        listaContactos.show();
        
        desktopPane.add(V1);
        int anchoDP = desktopPane.getWidth();  
        int LargoDP = desktopPane.getHeight();  
        int anchoV = V1.getWidth();  
        int LargoV = V1.getHeight();
        V1.setLocation((anchoDP)-(anchoV)-7, (LargoDP/2)-(LargoV/2));
        V1.show();
        ventanaChat.setVentanaChat(V1);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            for(int i=0;i<2;i++)
            {
                Socket sSalir=new Socket("192.168.0.13",7777);
                PrintWriter out=new PrintWriter(sSalir.getOutputStream(),true);
                out.println(
                        "<|emisor:|></|emisor:|>"+
                        "<|receptor:|></|receptor:|>"+
                        "<|mensaje:|>");
                out.flush();
                sSalir.close();
                try {
                    System.out.print("k");
                    Thread.sleep(4000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(General.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (UnknownHostException ex) {
            
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
