/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;

/**
 *
 * @author Nano
 */
public class VentanaChat extends javax.swing.JInternalFrame {

    Usuario xUsuario=new Usuario();
    ClaseListaContactos ContenidoListaContactos=new ClaseListaContactos();
    TabbledPane PanelVentanas=new TabbledPane();
    ArrayList<CArchivoCompartido> listaCompartidos=new ArrayList<CArchivoCompartido>();
    /**
     * Creates new form VentanaChat
     */
    public VentanaChat() {
        initComponents();
        setLayout(new GridLayout());
        PanelVentanas.setBounds(7, 7, 626, 359);
        PanelVentanas.setVisible(true);
        add(PanelVentanas);
        
        PanelVentanas.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                for(int CantidadbtnCon=0;CantidadbtnCon<ContenidoListaContactos.getContenedor().getComponentCount();CantidadbtnCon++)
                {
                    if(PanelVentanas.getComponentCount()>0)
                    {
                        if(ContenidoListaContactos.getContenedor().getComponent(CantidadbtnCon).getName().toUpperCase().equals(PanelVentanas.getComponent(PanelVentanas.getSelectedIndex()).getName().toUpperCase()))
                        {
                            ContenidoListaContactos.getContenedor().getComponent(CantidadbtnCon).setBackground(Color.orange);
                        }
                    }
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
                try
                {
                    setFocusEnvio();
                }
                catch(Exception ex){}
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
                
            }
        });
    }
    public void setFocusEnvio()
    {
        Component Componente=PanelVentanas.getComponent(PanelVentanas.getSelectedIndex());
        Component txtFocusScala0=((javax.swing.JPanel) Componente).getComponent(1);
        ((javax.swing.JTextField) txtFocusScala0).grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Chat KAAF");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        ClaseListaContactos ListaContainer=new ClaseListaContactos();
        new Cliente(xUsuario.getUsuario(),PanelVentanas,ListaContainer.getContenedor(),listaCompartidos,this).start();
        ServidorArchivos servidorArchivos=new ServidorArchivos(listaCompartidos);
        this.setTitle("Nombre de Usuario: "+xUsuario.getUsuario());
    }//GEN-LAST:event_formInternalFrameOpened

    private void PanelVentanasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVentanasMousePressed
        
    }//GEN-LAST:event_PanelVentanasMousePressed

    private void PanelVentanasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelVentanasMouseClicked
        
    }//GEN-LAST:event_PanelVentanasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
